- name: setup Mysql with db and remote login
  become: yes
  hosts: all
  tasks:
    - name: Installing Mysql  and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
        - mysql-server
        - mysql-client 
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: creating mysql user
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present
    - name: creating db
      mysql_db:
        name: "{{db_name}}"
        state: present
    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted


- name: setup Mysql with db and remote login
  become: yes
  hosts: all
  tasks:
    - name: Include environment-specific variables
      include_vars: "vars_{{ env }}.yml"
    - name: Installing Mysql and dependencies
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ mysql_packages }}"
      become: yes
    - name: start and enable mysql service
      service:
        name: "{{ mysql_service }}"
        state: started
        enabled: yes